yihui/xaringan

- DESCRIPTION
- inst/rmarkdown/templates/xaringan/resources/default.html
Adds a unique class name, `title-slide`, to the title/seal slide so it is possible to make specific changes to the css that are applicable only to the title page such as adding an institution logo, changing font size etc.
> Add unique class to title slide

- R/render.R
- inst/rmarkdown/templates/xaringan/resources/countdown.js
- man/moon_reader.Rd
Added code to include an optional countdown timer on each slide. The timer can be used with or without autoplay. Using the timer does require that incremental slides are counted in the total. The counter argument displays time in seconds. The counter turns red if the timer goes negative.
> adding countdown

- inst/rmarkdown/templates/xaringan/resources/default.html
MathJax CDN shutting down on April 30, 2017.
https://www.mathjax.org/cdn-shutting-down/
So, I replaced from `cdn.mathjax.org` to alternative CDN providers.
> replacement mathjax CDN

- inst/rmarkdown/templates/xaringan/resources/fonts-rladies.css
- inst/rmarkdown/templates/xaringan/resources/rladies.css
In response to your blog post!
https://yihui.name/en/2017/10/xaringan-themes/
> add rladies.css

- R/utils.R
- tests/testit/test-utils.R
Line highlighting is an excellent feature, but I've found that the need to wrap a complete expression in the brace fences `{{ ...code.. }}` to be a little tricky at times.
My two pain points have been:
1. The code in the chunk looks different than it's rendered, and the alignment of wrapped lines in the source is off by one character (see #70).
2. I often don't get the fencing right on the first try because I include a character that is part of a longer expression and therefore the braced section isn't correct. For example, you can't just wrap a line in `{{ ...line... }}`, you have to make sure you get just the part of the line that is an expression: `{{arg = "something"}},` (note the trailing comma).
I realized I could get around this with a custom knitr source hook, but for the sake of …
> Feature suggestion: New line highlight marker `#<<`

- NEWS.md
- R/render.R
- R/utils.R
This addresses #129 by adding an error message when a requested built-in theme is not available.
I named the check function `check_builtin_css()` as `check_css()` seemed ambiguous on second thought.
Personally, I like the behavior of xaringan with this PR a lot. If an incorrect theme is given, say `metropolis-font`, the error message is immediate. This helps signal that it's a configuration issue rather than an issue with code in the presentation. Also, the error message is helpful.
```
Error: "metropolis-font" is not a valid xaringan theme, did you mean "metropolis-fonts"?
Use `xaringan:::list_css()` to view all themes.
Execution halted
```
The error stops on the first invalid theme name. This seemed a reasonable trade-off between returning a useful error message and adding the logic …
> Check built-in themes with check_builtin_css() before render

- DESCRIPTION
- NEWS.md
- R/render.R
- inst/rmarkdown/templates/xaringan/resources/default.html
- inst/rmarkdown/templates/xaringan/skeleton/skeleton.Rmd
- man/moon_reader.Rd
This PR follows up on issue #136 (allowing users to specify the title slide classes from the `nature` argument of `moon_reader`).
- I added a `titleSlideClass` argument to `nature` in `moon_reader` that takes a character vector (or single string) and passes to the associated pandoc argument. I chose camel case for consistency with the other arguments to `nature`.
- I added a `title-slide-class` variable to the `default.html` pandoc template.
- I added a slide to the "Some Tips" section of the xaringan overview slides with instructions on using `titleSlideClass` and also on using `seal = FALSE` to remove the title slide. (Added as a separate commit so you can easily revert if not desired.)
- I updated the roxygen documentation for `moon_reader` in `R/render.R`, but I did not re-generate …
> Add title slide class arguments

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/xaringan/resources/kunoichi.css
- inst/rmarkdown/templates/xaringan/resources/ninjutsu.css
- inst/rmarkdown/templates/xaringan/resources/shinobi.css
I'm adding two xaringan themes - `shinobi.css` and `kunoichi.css` (which act like -fonts.css of other themes). Both of these are powered by `ninjutsu.css`. For an example of the functionality see https://emitanaka.github.io/ninja-theme/kunoichi-theme-example.html
> adding the ninja theme

- DESCRIPTION
- NEWS.md
- R/render.R
- R/utils.R
This PR adds a chunk hook for highlighting R output. It essentially adds two chunk options, `highlight.output` and `highlight.lines`. `highlight.output = TRUE` will highlight all outputted lines, while `highlight.lines` takes a vector of line numbers and highlights those lines, e.g. `highlight.lines = 5:8`.
Here are some examples
> Add highlighting for output

- DESCRIPTION
when installing the package I currently get:
```
Downloading GitHub repo yihui/xaringan@master
✔  checking for file ‘/tmp/RtmpM0LCI1/remotes436466f2bc88/yihui-xaringan-b520b7b/DESCRIPTION’
─  preparing ‘xaringan’:
E  checking DESCRIPTION meta-information
Malformed package version.
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
```
> fix typo in version number

- R/render.R
- inst/rmarkdown/templates/xaringan/resources/js/highlight-pre-parent.js
This PR adds a small amount of JS to add the class `.remark-code-has-line-highlighted` to the `<pre>` parent element of highlighted lines (which have the `.remark-code-line-highlighted` class).
This allows users to write CSS that targets code blocks containing highlighted lines, enabling effects such as the one proposed by @malcolmbarrett in #210. I've also created a [small demo here](https://gadenbuie.github.io/xaringan-line-focus).
I wasn't completely sure of the desired mechanism for including the JS file, but I followed a similar pattern to that used by the autoplay and countdown scripts and the required JS is only included when `isTRUE(nature$highlightLines)`. I'd be happy to reconfigure as needed.
> Add remark-code-has-line-highlighted class to pre parents of highlighted lines

- NEWS.md
- inst/examples/ki-demo.Rmd
- inst/rmarkdown/templates/xaringan/resources/ki-fonts.css
- inst/rmarkdown/templates/xaringan/resources/ki.css
Hi,
I added a couple of css files for a theme following the [Karolinska Institutet](https://staff.ki.se/download-karolinska-institutets-logo) visual identity guidelines.
Thanks!
Alessandro
> Karolinska Institutet theme

- NEWS.md
- R/render.R
- man/decktape.Rd
- man/moon_reader.Rd
To revert temporarily back to the old version of remark.js (prior to 0.15.0) in order to fix issue #245 
If we decide to go forward with this PR I suggest putting in a milestone so we remember to update the reference such that it points to the most recent version of remark.js once that has stabilized again with the new maintainer.
Thank you!
> pin remark.js version to v0.14

- DESCRIPTION
- NEWS.md
- R/render.R
- man/inf_mr.Rd
- tests/testit/parameterized.Rmd
- tests/testit/test-render.R
Resolves #253 - `inf_mr` and friends were failing on reports that had `params` as an argument in the front-matter. 
This was due to the object `params` being defined in the scope of `infinite_moon_reader`, which enclosed a call to `rmarkdown::render`. `rmarkdown::render` doesn't like it when there is a `params` object in the enclosing environment.
The following document now renders:
````pandoc
---
title: "Params Error"
subtitle: "Makes me sad"
author: "mstr3336"
institute: "mstr3336"
date: "`r Sys.Date()`"
params:
foo: oof
bar: rab
baz: zab
output:
xaringan::moon_reader:
lib_dir: libs
nature:
highlightStyle: github
highlightLines: true
countIncrementalSlides: false
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```
```{r display}
for (nm in names(params)) { …
> Fix infinite_moon_reader rendering of parameterized reports (#253)

- DESCRIPTION
following changes in #254. 
We don't use .9000 convention in this repository
See https://github.com/yihui/xaringan/commit/71b0b39d617c4d230882cfe60c32dd7f8aa63a3e and https://github.com/yihui/xaringan/commit/85c0e7f268ba94306bb33f2cfb70ad846d03b9ad
Thank you!
> put back the correct version numbering

- DESCRIPTION
- NEWS.md
- R/render.R
- inst/rmarkdown/templates/xaringan/resources/js/script-tags.js
A better implementation of the idea in #239, this time moving the `<script>` tags in the browser.
- Only `<scripts>` that are children of `.remark-slides-area` and are not a continuation (`:not(.has-continuation)`) are moved.
- All scripts in `.remark-slides-area` are replaced with a comment that they can be found at the end of `<body>`
> Script tags in slides

- NEWS.md
- inst/rmarkdown/templates/xaringan/resources/js/script-tags.js
@yihui This resolves #257. The main problem that issue brought up is that script tags like
```html
<script type="application/json" data-for="a1b2c3">/* json */</script>
```
were being re-written into a bare script tag.
```html
<script>/* ...json... */</script>
```
This PR fixes the above by ensuring that attributes are copied to the replaced `<script>` tag (5b475a8).
In light of this, it seems like it might not be worth the effort to work around slide continuations, so I removed that portion of the script in c8c6294.
> Ensure attributes are copied to replaced script tags

- NEWS.md
- inst/rmarkdown/templates/xaringan/resources/default.css
- inst/rmarkdown/templates/xaringan/resources/fc.css
- inst/rmarkdown/templates/xaringan/resources/ki.css
- inst/rmarkdown/templates/xaringan/resources/middlebury.css
- inst/rmarkdown/templates/xaringan/resources/robot.css
- inst/rmarkdown/templates/xaringan/resources/rutgers.css
- inst/rmarkdown/templates/xaringan/resources/uol.css
This fixes the selector associated with the `.pull-right` class that currently clears left/right floats on *all* elements after a `.pull-right[]` div, rather than on the element _immediately after_ the `.pull-right`.
This is the root cause of #260 and ultimately causes misalignment of columns if multiple floats are used on a slide. With the default CSS `.pull-right ~ * { clear: both; }`, a second `.pull-right[]` appears on a new row.
Replaced with `.pull-right + * { clear: both; }`, multiple columns render as intended.
A few of the built-in themes were derived from `default.css`, so I updated those in a separate commit that can be reverted if desired.
> Clear floats only on element immediately after .pull-right

- NEWS.md
- R/render.R
- inst/rmarkdown/templates/xaringan/skeleton/skeleton.Rmd
- man/moon_reader.Rd
fixes #265 
Restarts the slideshow after the summed up time set in `autoplay` (default) or optionally after a user supplied time (in ms).
I'm not bound to the option name - feel free to change it.
Preview: https://pat-s.me/slides/xaringan-restart/skeleton.html
---
Thank you!
> Add nature option `restart_slideshow`

- DESCRIPTION
- NEWS.md
- R/render.R
- inst/rmarkdown/templates/xaringan/skeleton/skeleton.Rmd
- man/moon_reader.Rd
This was preventing xaringan to benefit from new sass support in rmarkdown 2.7 
`css` argument in `moon_reader()` is passed to `rmarkdown::html_document()` which support this sass files. So it should work correctly with `moon_reader()` too. 
@abichat can you check ?
> `.sass` and `.scss` are not built in themes like `.css` files.

- NEWS.md
- inst/rmarkdown/templates/xaringan/resources/useR.css
> Fixed lack of blue background color in useR chapter-slide

- DESCRIPTION
- NEWS.md
- R/utils.R
- inst/rmarkdown/templates/xaringan/resources/js/data-uri.js
> Added support for embedding media files from <audio src="..."> and <video src="..."> in the self-contained mode

- NEWS.md
- inst/examples/ki-demo.Rmd
- inst/rmarkdown/templates/xaringan/resources/ki-fonts.css
- inst/rmarkdown/templates/xaringan/resources/ki.css
Hi,
With this PR I am updating the KI theme to the [recently updated visual identity](https://news.ki.se/kis-updated-visual-identity-is-being-launched).
It is still work in progress so please do not merge yet – I am creating this to keep track of things and to upload a new, updated logo created specifically for digital channels.
I will give a couple of presentations next week using this template, so I'll confirm it's okay to merge after that if that's okay :smile:
Thanks!
Alessandro
> Updating KI theme to KI's recently updated visual identity
