inst/rmarkdown/templates/xaringan_zh-CN/skeleton/zh-CN.css

Deal with issue #8 and the screenshot of fixed would be uploaded later.

Make footnote appear within content container

---

R/render.R
man/moon_reader.Rd

render.R: add Github wiki link to moon_reader() help

---

NEWS.md

Forgot NEWS and apparently @ekstroem and I have no direct push access to the repo as the master branch is protected from direct commits. 
So another PR to merge :smile: 
I created a new NEWS session for "theme updates". Probably more to come in the future.

update NEWS with #107

---

DESCRIPTION
NEWS.md
inst/rmarkdown/templates/xaringan/resources/uo-fonts.css
inst/rmarkdown/templates/xaringan/resources/uo.css

Hi Yihui!
I added files for a theme for the University of Oregon. I'd be happy to make any revisions to these that you think might improve them. 
One thing I wasn't sure about was that the font size for the body seemed a little small to me, given the font I imported for the body. So I bumped it up a little, and I'm not sure if the approach I took to increasing it was the best. It was the only way I could get it to work (I couldn't get it to work at all for a while). I am certainly not a CSS expert and most of this I figured out through trial and error.  The theme basically works with the default presentation, but because of the bumped up font size there are a few slides that extend beyond the page.
Thanks for such an amazing package and all that you do!
Daniel

Added css files for UO theme

---

DESCRIPTION
NEWS.md
inst/rmarkdown/templates/xaringan/resources/robot-fonts.css
inst/rmarkdown/templates/xaringan/resources/robot.css

A roboto inspired theme (note: signed agreement upon seeing the check fail)

Uploaded robot theme files

---

NEWS.md
inst/rmarkdown/templates/xaringan/resources/middlebury-fonts.css
inst/rmarkdown/templates/xaringan/resources/middlebury.css

Includes middlebury.css and middlebury-fonts.css. 
Example presentation available here: https://www.jvcasillas.com/midd_xaringan/slides/index.html

Add Middlebury College templates

---

README.md

I'm not married to this particular phrasing or anything, but I think an emphasis that the `remark.js` website itself has a quick intro is helpful.

Related to #151 -- small clarification in README

---

DESCRIPTION
NEWS.md
inst/examples/lucy-demo.Rmd
inst/rmarkdown/templates/xaringan/resources/lucy-fonts.css
inst/rmarkdown/templates/xaringan/resources/lucy.css

* I have a template that matches the powerpoint (🙊) slides I usually make
* Let me know if you think it would be better for me to name this something more generic than `lucy` (I thought about something like `dark`, but maybe that's too broad?)
Thank you!

Add my css template

---

NEWS.md

Add news item for #220

---

.github/ISSUE_TEMPLATE.md
.travis.yml
NEWS.md
R/render.R
README.md
inst/examples/uol-demo.Rmd
inst/rmarkdown/templates/xaringan/skeleton/skeleton.Rmd
inst/rmarkdown/templates/xaringan_zh-CN/skeleton/skeleton.Rmd
man/decktape.Rd
vignettes/intro-en_US.Rhtml
vignettes/intro-zh_CN.Rhtml

Following https://github.com/rstudio/pagedown/issues/154 this changes the domain of the website in `travis.yml` where redirection are not handled by curl currently
should it be changed also anywhere in the source code ?
Do you want to handle only with redirection ? I am thinking it could be better to replace all

change domain for website in travis

---

DESCRIPTION
NEWS.md
R/render.R
man/decktape.Rd
man/inf_mr.Rd
man/moon_reader.Rd

Add the params argument to infinite_moon_reader()

---

NEWS.md
inst/rmarkdown/templates/xaringan/resources/ki.css

Hi,
With this PR I made some small changes/updates to the css for the KI theme after using it for a while.
Thanks,
Alessandro

Updates to KI theme

---

NEWS.md

> To contribute to this repo, please make sure to:
> 
> - [x] Sign the CLA http://www.clahub.com/agreements/yihui/xaringan (if you haven't signed it before).
> - [ ] Add a news item to NEWS.md and your name to DESCRIPTION (by alphabetical order) unless you have already been listed there.
> - [ ] Provide a URL to a live example (and even better, a couple of screenshots) if you are contributing a new theme.
> 
> Thank you!
I did sign the CLA but as this is a quick edit via the web interface, `DESCRIPTION` was left unmodified.
I doubt anyone would consider this a real contribution either way. :wink:
If you want me to add my name regardless, feel free to do so or let me know here and I'll clone locally and (force-)push the `DESCRIPTON` change.

Fix typo in NEWS

---

DESCRIPTION
NEWS.md
inst/rmarkdown/templates/xaringan/resources/useR-fonts.css
inst/rmarkdown/templates/xaringan/resources/useR.css

[skeleton.pdf](https://github.com/yihui/xaringan/files/5269289/skeleton.pdf)
Thank you!

Add the useR theme

---

DESCRIPTION
NEWS.md
inst/rmarkdown/templates/xaringan/resources/nhsr-fonts.css
inst/rmarkdown/templates/xaringan/resources/nhsr.css

Thank you!
👋 Hello Yihui!
This pull request adds the **nhsr theme** to the xaringan package -- a theme designed for (and with feedback from) the [NHS-R Community](https://github.com/nhs-r-community/), and following the [NHS identity guidelines](https://www.england.nhs.uk/nhsidentity/identity-guidelines/). 
The **nhsr theme** was designed in preparation for a [xaringan workshop](https://spcanelon.github.io/xaringan-basics-and-beyond/) created for the NHS-R 2020 Conference, and is also being contributed to the [`nhsrtheme` package](https://github.com/nhs-r-community/nhsrtheme) developed by [Tom Jemmett](https://github.com/tomjemmett).
- [Ratio 4:3](https://spcanelon.github.io/xaringan-basics-and-beyond/nhsr-theme/sample-4-3.html)
- [Ratio …

Adding the nhsr theme

---

inst/rmarkdown/templates/xaringan/resources/rutgers.css

Fix to a more specific comment

Update rutgers.css comment fix #294

---

DESCRIPTION
NEWS.md
inst/rmarkdown/templates/xaringan/resources/glasgow_template.css

commit new template

---

DESCRIPTION
NEWS.md
inst/rmarkdown/templates/xaringan/resources/uwm-fonts.css
inst/rmarkdown/templates/xaringan/resources/uwm.css

Thank you!
Hi Yihui,
This pull request adds the University of Wisconsin-Madison theme to the xaringan package. I used xaringan to create my prelim exam slides and I want to share this UW-Madison theme.
[live example](https://ttuowang.github.io/Xaringan-wisconsin-theme/#1)

Added UW-Madison theme

---

DESCRIPTION
NEWS.md
inst/rmarkdown/templates/xaringan/resources/useR.css

This will fix #326 by removing the empty `url()` declaration in the CSS. 
----------
Thank you!

Fix standalone mode for UseR theme

---

.Rbuildignore
.github/workflows/R-CMD-check.yaml
README.md
codecov.yml

This updates to using `r-lib/actions@v2` and also add codecov as other repo

Update GHA workflow

---

DESCRIPTION
NEWS.md
R/render.R

WIP: have inf_mr watch Rmd

---

DESCRIPTION
NEWS.md
inst/rmarkdown/templates/xaringan/resources/wic-fonts.css
inst/rmarkdown/templates/xaringan/resources/wic.css

Thank you!
Hi! 
I'm contributing with a theme that was developed by some colleagues at the Wittgenstein Centre (WIC) in accordance with the WIC identity guidelines.
[WIC slides example](https://olayabucaro.github.io/WICslides/)

Adding a wic theme

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/workflows/R-CMD-check.yaml
DESCRIPTION

Few tweaks - revert any commit that don't fit this repo

Spring cleaning work

---

NEWS.md

Update NEWS.md to include CSS changes in rutgers theme
